### PR TITLE
wrapLongLines + line numbering with wrapped lines

### LINKED ISSUE #235: Wrap long lines not working
**Describe the bug**
Long lines can't be wrapped, when trying to do with style `white-space: pre-wrap;` on the `pre code` element the line numbers get broken.

**To Reproduce**
1. Add new SyntaxHighlighter with long code of any king
2. Set style `white-space: pre-wrap;` on the `pre code` element
3. Scroll down to the bottom and see last lines without number

**Expected behavior**
Would expect to have build-in wrap long lines properly that will correctly wrap the lines and keep the correct numbering

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser  Chrome
 - Version 79.0.3945.88 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by simmerer**
Fixes #235 and introduces a few API & styling changes along the way.

1. New prop: `wrapLongLines`
2. New default prop value: `showInlineLineNumbers = true`
3. Explicit white-space styling on `<code>` tag

## 1. New prop: "wrapLongLines"

`wrapLongLines` takes care of adding `white-space: pre-wrap` styling to the `<code>` tag: no need to do this yourself via CSS or `codeTagProps` anymore.

There are a few potential consequences of this new prop.

### Containing elements around each line

If you've set `wrapLongLines={true}`, React Syntax Highlighter will wrap each line of code in its own `<span>`, just as if you'd explicitly set `wrapLines={true}`.

This could be a breaking change for anyone who is currently:
- manually setting `white-space: pre-wrap` on their `<code>` element
- has `wrapLines={false}` or is using Prism, which defaults to _not_ creating containing elements around each line's elements
- is theming with CSS direct-descendant selectors that would break if there was a containing element around each line's elements

> `wrapLines` is another awkward prop name that should eventually be changed, because it affects containing elements, not text-wrapping. `wrapLongLines` now actually does what some people mistakenly thought `wrapLines` would do.

### display: flex to provide long-line wrapping that doesn't flow into the line number area

If you're using `wrapLongLines={true}` and are showing line numbers (`showLineNumbers={true}`), we'll now style each line element with `display: flex`.

This overrides the `display: block` styling that most themes apply to each line.

**Probably won't be a noticeable change for most users, but if you see any unexpected `line-height` changes with this change, that's probably the cause.**

## 2. New default prop value (potentially breaking change)
`showInlineLineNumbers = true`

The old default for line numbering (`showLineNumbers` + `showInlineLineNumbers = false`) created a separate `<code>` element containing all line numbers.

This was problematic when using a virtualized renderer or when applying `white-space: pre-wrap` to the code area. Since having line numbers inside each line element is advantageous in several cases, I think it should become the default method of rendering line numbers.

> `showInlineLineNumbers` is confusingly named, I admit: it should have been "preferInlineNumbering" or "putLineNumbersInline", since `showLineNumbers` is still the prop that controls whether or not line numbers are visible at all.

## 3. Explicit white-space styling on `<code>` tag (potentially breaking change)

In order to set `white-space: pre-wrap` when `wrapLongLines={true}`, RSH now explicitly sets `white-space: pre` when in the default state of `wrapLongLines={false}`. If you've manually applied `white-space: pre-wrap` via `codeTagProps` or your theme CSS, this might override your intended styling.

The workaround here is to migrate to using the new `wrapLongLines={true}` prop, which will provide the `pre-wrap` styling for you.

### CODE REVIEW

File: src/highlight.js [hunk 1]
```diff
@@ -115,6 +117,12 @@ function createLineElement({
     children.unshift(getInlineLineNumber(lineNumber, inlineLineNumberStyle));
   }
 
+  if (wrapLongLines & showLineNumbers) {
+    properties.style
+      ? (properties.style['display'] = 'flex')
+      : (properties.style = { display: 'flex' });
```
Comment (karlhorky) [inline src/highlight.js:123]: I guess these (and also the other 2 occurrences down below) could also be written like this:

```js
properties.style = { ...properties.style, display: 'flex' }
```

Even if `properties.style` is `undefined`, this still works.

File: src/highlight.js [hunk 2]
```diff
@@ -367,7 +379,8 @@ export default function(defaultAstGenerator, defaultStyle) {
      * some custom renderers rely on individual row elements so we need to turn wrapLines on
      * if renderer is provided and wrapLines is undefined
      */
-    wrapLines = renderer && wrapLines === undefined ? true : wrapLines;
+    wrapLines =
+      (renderer || wrapLongLines) && wrapLines === undefined ? true : wrapLines;
```
Comment (karlhorky) [inline src/highlight.js:383]: Maybe this would be easier to read like this:

```js
if (wrapLines === undefined && (renderer || wrapLongLines)) {
  wrapLines = true;
}
```

File: src/highlight.js (hunk 1 above)
Comment (simmerer) [reply src/highlight.js:123]: Nice, that's much better
